name: Build and Sign Android AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
